name: upload-html-to-droplet
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  validate-html: 
    runs-on: ubuntu-latest
    steps: 
      - uses: anishathalye/proof-html@v2
        with:
            directory: ./html
