name: validate-html
run-name: Validate HTML
on: [push]
jobs:
  validate-html: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5-validator-action
        with:
            root: ${{ github.workspace }}/html
