name: validate-html
run-name: Validate HTML
on: [push]
jobs:
  validate-html: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
            root: ${{ github.workspace }}/html
